name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest minor versions of Go 1.21 and 1.22
        go-version: ["1.21.x", "1.22.x", "1.23.x"]
        include:
          # only update test coverage stats with Go 1.23
          - go-version: "1.23.x"
            update-coverage: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go tests with coverage
        run: make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ matrix.update-coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
